#!/usr/bin/env python
"""
vmd_rdf.py — Compute all-pair RDFs from a LAMMPS dump using VMD

Usage (CLI):
    python vmd_rdf.py dump.lammpstrj [rmax] [dr]

Usage (Python):
    import vmd_rdf
    vmd_rdf.compute_allpairs("dump.lammpstrj", rmax=10.0, dr=0.05)
"""

import os
import subprocess
import tempfile
from pathlib import Path


def compute_allpairs(dumpfile, rmax=10.0, dr=0.05, vmd_path="vmd"):
    """
    Compute all-pair RDFs (no PBC) using VMD in text mode.

    Parameters
    ----------
    dumpfile : str
        Path to LAMMPS dump file (.lammpstrj)
    rmax : float, optional
        Maximum distance (Å), default = 10.0
    dr : float, optional
        Bin width (Å), default = 0.05
    vmd_path : str, optional
        Path to VMD executable (default assumes it's in PATH)

    Output
    ------
    Writes RDF data files like '1-1.dat', '1-2.dat', etc.
    """
    dumpfile = str(Path(dumpfile).resolve())

    # --- Check dump file ---
    if not os.path.isfile(dumpfile):
        raise FileNotFoundError(f"❌ File not found: {dumpfile}")

    # --- Inline TCL script for VMD ---
    tcl_script = f"""\
# --- autogenerated by vmd_rdf.py ---
set dumpfile "{dumpfile}"
set rmax {rmax}
set dr {dr}

puts "📂 Loading $dumpfile ..."
mol new $dumpfile type lammpstrj waitfor all
set nframes [molinfo top get numframes]
puts "✅ Loaded $nframes frames"

set allsel [atomselect top "all"]
set types [lsort -unique [$allsel get type]]
puts "Atom types detected: $types"

foreach type1 $types {{
    foreach type2 $types {{
        if {{ [string compare $type1 $type2] <= 0 }} {{
            puts "Computing RDF for $type1-$type2 ..."

            set sel1 [atomselect top "type $type1"]
            set sel2 [atomselect top "type $type2"]

            set gr [measure gofr $sel1 $sel2 delta $dr rmax $rmax usepbc false selupdate false first 0 last [expr {{$nframes - 1}}] step 1]
            set r [lindex $gr 0]
            set g [lindex $gr 1]
            set int [lindex $gr 2]

            set fname "${{type1}}-${{type2}}.dat"
            set out [open $fname w]
            puts $out "# r  g(r)  int(g(r))"
            for {{set i 0}} {{$i < [llength $r]}} {{incr i}} {{
                puts $out "[lindex $r $i] [lindex $g $i] [lindex $int $i]"
            }}
            close $out
            puts " → wrote $fname"
        }}
    }}
}}

puts "✅ All RDFs written."
exit
"""

    # --- Create temporary Tcl script ---
    with tempfile.NamedTemporaryFile("w", delete=False, suffix=".tcl") as tmpfile:
        tmpfile.write(tcl_script)
        tmpfile_path = tmpfile.name

    # --- Run VMD ---
    try:
        subprocess.run(
            [vmd_path, "-dispdev", "text", "-e", tmpfile_path],
            check=True,
        )
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"❌ VMD execution failed: {e}")
    finally:
        # Always clean up
        if os.path.exists(tmpfile_path):
            os.remove(tmpfile_path)

    print("✅ RDF computation finished successfully via VMD.")


# --- CLI Entry Point ---
if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python vmd_rdf.py dump.lammpstrj [rmax] [dr]")
        sys.exit(1)

    dumpfile = sys.argv[1]
    rmax = float(sys.argv[2]) if len(sys.argv) > 2 else 10.0
    dr = float(sys.argv[3]) if len(sys.argv) > 3 else 0.05

    compute_allpairs(dumpfile, rmax, dr)
